name: e2e
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.10.0"

resolution: workspace

dependencies:
  analyzer: ^9.0.0
  analyzer_buffer: ^0.1.5
  build: ^4.0.0
  build_config: ^1.1.0
  collection: ^1.15.0
  flutter:
    sdk: flutter
  meta: ^1.16.0
  path: ^1.9.1
  source_gen: ^4.0.0

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^3.0.0
  matcher: ^0.12.14
  other:
  test: ^1.21.0